export const SET_SHOW_CALENDAR = 'SET_SHOW_CALENDAR';
export const SET_DATE_VALUE = 'SET_DATE_VALUE';
export const SET_MIN_DATE_VALUE = 'SET_MIN_DATE_VALUE';
export const SET_MAX_DATE_VALUE = 'SET_MAX_DATE_VALUE';