// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class CalendarHoliday
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject calendarHolidayMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.CalendarHoliday";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DateFrom("DateFrom"),
		DateTo("DateTo"),
		Active("Active"),
		CalendarHoliday_ConfigCalendar("MyFirstModule.CalendarHoliday_ConfigCalendar");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CalendarHoliday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CalendarHoliday(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject calendarHolidayMendixObject)
	{
		if (calendarHolidayMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, calendarHolidayMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.calendarHolidayMendixObject = calendarHolidayMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'CalendarHoliday.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.CalendarHoliday initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.CalendarHoliday.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.CalendarHoliday initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CalendarHoliday(context, mendixObject);
	}

	public static myfirstmodule.proxies.CalendarHoliday load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CalendarHoliday.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CalendarHoliday> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.CalendarHoliday.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom()
	{
		return getDateFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of DateFrom
	 */
	public final java.util.Date getDateFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateFrom.toString());
	}

	/**
	 * Set value of DateFrom
	 * @param datefrom
	 */
	public final void setDateFrom(java.util.Date datefrom)
	{
		setDateFrom(getContext(), datefrom);
	}

	/**
	 * Set value of DateFrom
	 * @param context
	 * @param datefrom
	 */
	public final void setDateFrom(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date datefrom)
	{
		getMendixObject().setValue(context, MemberNames.DateFrom.toString(), datefrom);
	}

	/**
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo()
	{
		return getDateTo(getContext());
	}

	/**
	 * @param context
	 * @return value of DateTo
	 */
	public final java.util.Date getDateTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateTo.toString());
	}

	/**
	 * Set value of DateTo
	 * @param dateto
	 */
	public final void setDateTo(java.util.Date dateto)
	{
		setDateTo(getContext(), dateto);
	}

	/**
	 * Set value of DateTo
	 * @param context
	 * @param dateto
	 */
	public final void setDateTo(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateto)
	{
		getMendixObject().setValue(context, MemberNames.DateTo.toString(), dateto);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CalendarHoliday_ConfigCalendar
	 */
	public final myfirstmodule.proxies.ConfigCalendar getCalendarHoliday_ConfigCalendar() throws com.mendix.core.CoreException
	{
		return getCalendarHoliday_ConfigCalendar(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarHoliday_ConfigCalendar
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.ConfigCalendar getCalendarHoliday_ConfigCalendar(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.ConfigCalendar result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CalendarHoliday_ConfigCalendar.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.ConfigCalendar.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CalendarHoliday_ConfigCalendar
	 * @param calendarholiday_configcalendar
	 */
	public final void setCalendarHoliday_ConfigCalendar(myfirstmodule.proxies.ConfigCalendar calendarholiday_configcalendar)
	{
		setCalendarHoliday_ConfigCalendar(getContext(), calendarholiday_configcalendar);
	}

	/**
	 * Set value of CalendarHoliday_ConfigCalendar
	 * @param context
	 * @param calendarholiday_configcalendar
	 */
	public final void setCalendarHoliday_ConfigCalendar(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ConfigCalendar calendarholiday_configcalendar)
	{
		if (calendarholiday_configcalendar == null) {
			getMendixObject().setValue(context, MemberNames.CalendarHoliday_ConfigCalendar.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CalendarHoliday_ConfigCalendar.toString(), calendarholiday_configcalendar.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return calendarHolidayMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CalendarHoliday that = (myfirstmodule.proxies.CalendarHoliday) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
