// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ConfigCalendar
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configCalendarMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ConfigCalendar";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MinNoBusinessDay("MinNoBusinessDay"),
		EnableWorkMonday("EnableWorkMonday"),
		EnableWorkTuesday("EnableWorkTuesday"),
		EnableWorkWednesday("EnableWorkWednesday"),
		EnableWorkThursday("EnableWorkThursday"),
		EnableWorkFriday("EnableWorkFriday"),
		EnableWorkSaturday("EnableWorkSaturday"),
		EnableWorkSunday("EnableWorkSunday"),
		ConfigCalendar_Request("MyFirstModule.ConfigCalendar_Request");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConfigCalendar(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConfigCalendar(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configCalendarMendixObject)
	{
		if (configCalendarMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configCalendarMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configCalendarMendixObject = configCalendarMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ConfigCalendar.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.ConfigCalendar initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.ConfigCalendar.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.ConfigCalendar initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ConfigCalendar(context, mendixObject);
	}

	public static myfirstmodule.proxies.ConfigCalendar load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ConfigCalendar.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ConfigCalendar> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.ConfigCalendar.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of MinNoBusinessDay
	 */
	public final java.lang.Integer getMinNoBusinessDay()
	{
		return getMinNoBusinessDay(getContext());
	}

	/**
	 * @param context
	 * @return value of MinNoBusinessDay
	 */
	public final java.lang.Integer getMinNoBusinessDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinNoBusinessDay.toString());
	}

	/**
	 * Set value of MinNoBusinessDay
	 * @param minnobusinessday
	 */
	public final void setMinNoBusinessDay(java.lang.Integer minnobusinessday)
	{
		setMinNoBusinessDay(getContext(), minnobusinessday);
	}

	/**
	 * Set value of MinNoBusinessDay
	 * @param context
	 * @param minnobusinessday
	 */
	public final void setMinNoBusinessDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minnobusinessday)
	{
		getMendixObject().setValue(context, MemberNames.MinNoBusinessDay.toString(), minnobusinessday);
	}

	/**
	 * @return value of EnableWorkMonday
	 */
	public final java.lang.Boolean getEnableWorkMonday()
	{
		return getEnableWorkMonday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkMonday
	 */
	public final java.lang.Boolean getEnableWorkMonday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkMonday.toString());
	}

	/**
	 * Set value of EnableWorkMonday
	 * @param enableworkmonday
	 */
	public final void setEnableWorkMonday(java.lang.Boolean enableworkmonday)
	{
		setEnableWorkMonday(getContext(), enableworkmonday);
	}

	/**
	 * Set value of EnableWorkMonday
	 * @param context
	 * @param enableworkmonday
	 */
	public final void setEnableWorkMonday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworkmonday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkMonday.toString(), enableworkmonday);
	}

	/**
	 * @return value of EnableWorkTuesday
	 */
	public final java.lang.Boolean getEnableWorkTuesday()
	{
		return getEnableWorkTuesday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkTuesday
	 */
	public final java.lang.Boolean getEnableWorkTuesday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkTuesday.toString());
	}

	/**
	 * Set value of EnableWorkTuesday
	 * @param enableworktuesday
	 */
	public final void setEnableWorkTuesday(java.lang.Boolean enableworktuesday)
	{
		setEnableWorkTuesday(getContext(), enableworktuesday);
	}

	/**
	 * Set value of EnableWorkTuesday
	 * @param context
	 * @param enableworktuesday
	 */
	public final void setEnableWorkTuesday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworktuesday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkTuesday.toString(), enableworktuesday);
	}

	/**
	 * @return value of EnableWorkWednesday
	 */
	public final java.lang.Boolean getEnableWorkWednesday()
	{
		return getEnableWorkWednesday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkWednesday
	 */
	public final java.lang.Boolean getEnableWorkWednesday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkWednesday.toString());
	}

	/**
	 * Set value of EnableWorkWednesday
	 * @param enableworkwednesday
	 */
	public final void setEnableWorkWednesday(java.lang.Boolean enableworkwednesday)
	{
		setEnableWorkWednesday(getContext(), enableworkwednesday);
	}

	/**
	 * Set value of EnableWorkWednesday
	 * @param context
	 * @param enableworkwednesday
	 */
	public final void setEnableWorkWednesday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworkwednesday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkWednesday.toString(), enableworkwednesday);
	}

	/**
	 * @return value of EnableWorkThursday
	 */
	public final java.lang.Boolean getEnableWorkThursday()
	{
		return getEnableWorkThursday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkThursday
	 */
	public final java.lang.Boolean getEnableWorkThursday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkThursday.toString());
	}

	/**
	 * Set value of EnableWorkThursday
	 * @param enableworkthursday
	 */
	public final void setEnableWorkThursday(java.lang.Boolean enableworkthursday)
	{
		setEnableWorkThursday(getContext(), enableworkthursday);
	}

	/**
	 * Set value of EnableWorkThursday
	 * @param context
	 * @param enableworkthursday
	 */
	public final void setEnableWorkThursday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworkthursday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkThursday.toString(), enableworkthursday);
	}

	/**
	 * @return value of EnableWorkFriday
	 */
	public final java.lang.Boolean getEnableWorkFriday()
	{
		return getEnableWorkFriday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkFriday
	 */
	public final java.lang.Boolean getEnableWorkFriday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkFriday.toString());
	}

	/**
	 * Set value of EnableWorkFriday
	 * @param enableworkfriday
	 */
	public final void setEnableWorkFriday(java.lang.Boolean enableworkfriday)
	{
		setEnableWorkFriday(getContext(), enableworkfriday);
	}

	/**
	 * Set value of EnableWorkFriday
	 * @param context
	 * @param enableworkfriday
	 */
	public final void setEnableWorkFriday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworkfriday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkFriday.toString(), enableworkfriday);
	}

	/**
	 * @return value of EnableWorkSaturday
	 */
	public final java.lang.Boolean getEnableWorkSaturday()
	{
		return getEnableWorkSaturday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkSaturday
	 */
	public final java.lang.Boolean getEnableWorkSaturday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkSaturday.toString());
	}

	/**
	 * Set value of EnableWorkSaturday
	 * @param enableworksaturday
	 */
	public final void setEnableWorkSaturday(java.lang.Boolean enableworksaturday)
	{
		setEnableWorkSaturday(getContext(), enableworksaturday);
	}

	/**
	 * Set value of EnableWorkSaturday
	 * @param context
	 * @param enableworksaturday
	 */
	public final void setEnableWorkSaturday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworksaturday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkSaturday.toString(), enableworksaturday);
	}

	/**
	 * @return value of EnableWorkSunday
	 */
	public final java.lang.Boolean getEnableWorkSunday()
	{
		return getEnableWorkSunday(getContext());
	}

	/**
	 * @param context
	 * @return value of EnableWorkSunday
	 */
	public final java.lang.Boolean getEnableWorkSunday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EnableWorkSunday.toString());
	}

	/**
	 * Set value of EnableWorkSunday
	 * @param enableworksunday
	 */
	public final void setEnableWorkSunday(java.lang.Boolean enableworksunday)
	{
		setEnableWorkSunday(getContext(), enableworksunday);
	}

	/**
	 * Set value of EnableWorkSunday
	 * @param context
	 * @param enableworksunday
	 */
	public final void setEnableWorkSunday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean enableworksunday)
	{
		getMendixObject().setValue(context, MemberNames.EnableWorkSunday.toString(), enableworksunday);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfigCalendar_Request
	 */
	public final myfirstmodule.proxies.Request getConfigCalendar_Request() throws com.mendix.core.CoreException
	{
		return getConfigCalendar_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigCalendar_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Request getConfigCalendar_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigCalendar_Request.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Request.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfigCalendar_Request
	 * @param configcalendar_request
	 */
	public final void setConfigCalendar_Request(myfirstmodule.proxies.Request configcalendar_request)
	{
		setConfigCalendar_Request(getContext(), configcalendar_request);
	}

	/**
	 * Set value of ConfigCalendar_Request
	 * @param context
	 * @param configcalendar_request
	 */
	public final void setConfigCalendar_Request(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Request configcalendar_request)
	{
		if (configcalendar_request == null) {
			getMendixObject().setValue(context, MemberNames.ConfigCalendar_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfigCalendar_Request.toString(), configcalendar_request.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configCalendarMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ConfigCalendar that = (myfirstmodule.proxies.ConfigCalendar) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
