// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Request
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestDate("RequestDate"),
		ConfigCalendar_Request("MyFirstModule.ConfigCalendar_Request");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject requestMendixObject)
	{
		if (requestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, requestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.requestMendixObject = requestMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Request.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Request.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Request(context, mendixObject);
	}

	public static myfirstmodule.proxies.Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Request.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Request> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Request.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RequestDate
	 */
	public final java.util.Date getRequestDate()
	{
		return getRequestDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestDate
	 */
	public final java.util.Date getRequestDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestDate.toString());
	}

	/**
	 * Set value of RequestDate
	 * @param requestdate
	 */
	public final void setRequestDate(java.util.Date requestdate)
	{
		setRequestDate(getContext(), requestdate);
	}

	/**
	 * Set value of RequestDate
	 * @param context
	 * @param requestdate
	 */
	public final void setRequestDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requestdate)
	{
		getMendixObject().setValue(context, MemberNames.RequestDate.toString(), requestdate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ConfigCalendar_Request
	 */
	public final myfirstmodule.proxies.ConfigCalendar getConfigCalendar_Request() throws com.mendix.core.CoreException
	{
		return getConfigCalendar_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of ConfigCalendar_Request
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.ConfigCalendar getConfigCalendar_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.ConfigCalendar result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ConfigCalendar_Request.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.ConfigCalendar.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ConfigCalendar_Request
	 * @param configcalendar_request
	 */
	public final void setConfigCalendar_Request(myfirstmodule.proxies.ConfigCalendar configcalendar_request)
	{
		setConfigCalendar_Request(getContext(), configcalendar_request);
	}

	/**
	 * Set value of ConfigCalendar_Request
	 * @param context
	 * @param configcalendar_request
	 */
	public final void setConfigCalendar_Request(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.ConfigCalendar configcalendar_request)
	{
		if (configcalendar_request == null) {
			getMendixObject().setValue(context, MemberNames.ConfigCalendar_Request.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ConfigCalendar_Request.toString(), configcalendar_request.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return requestMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Request that = (myfirstmodule.proxies.Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
